version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongogRPC
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=gRPCMongo
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=